questions =  [
    {"id": 0, "question": "Freedom of business is the best practical way a society can prosper.", "effects": {"right": 1}},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "Employers never know what their employees labour is worth.", "effects": {"right": -1}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "Taxation of the wealthy is a bad idea, society would be better off without it.", "effects": {"right": 1}},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"right": 1}},
    {"id": 8, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 9, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 12, "question": "All industry and the bank should be nationalised.", "effects": {"right": -1}},
    {"id": 13, "question": "Class is the primary division of society.", "effects": {"right": -1}},
    {"id": 14, "question": "Economic inequality is too high in the world.", "effects": {"right": -1}},
    {"id": 15, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 16, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 17, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 18, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 19, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 20, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 22, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 23, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "Without democracy, a society is nothing.", "effects": {"auth": -1}},
    {"id": 25, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 26, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 27, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 28, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}},
    {"id": 46, "question": "Governments subsidising the market makes more inequality than private corporations.", "effects": {"right": 1, "auth": -1}},
    {"id": 47, "question": "Equal representation and opportunity for all citizens is the cornerstone of a just society.", "effects": {"prog": 1, "auth":-1}},
    {"id": 48, "question": "The right to bear arms should be balanced with responsible gun control measures.", "effects": {"auth":0.5}},
    {"id": 49, "question": "If something is too expensive, people won't buy it.", "effects": {"right":1}},
    {"id": 50, "question": "Intervention in other countries for our own interests is totally fair.", "effects": {"auth":1}},
    {"id": 51, "question": "There should be no bicameral system - only monocameral.", "effects": {"auth":1}},
    {"id": 52, "question": "Putting checks and balances in place is useful to assure that no one figure has all the power.", "effects": {"auth":-1}},
    {"id": 53, "question": "Taxation causes more inequality than the market by taking away wages from hard-working people.", "effects": {"right":1}},
    {"id": 54, "question": "Someone's labour should matter more than their status.", "effects": {"right":1, "auth":-1}},
    {"id": 55, "question": "Media products that contained frowned-upon language should be revised to be more progressive, even if it makes them unrealistic.", "effects": {"prog":1}},
    {"id": 56, "question": "National Socialism was more communist than capitalist.", "effects": {"right":1}},
    {"id": 57, "question": "Fascism is to capitalism what communism is to socialism.", "effects": {"right":-1}},
    {"id": 58, "question": "A fully unregulated market will always lead to corporatocracy and hegemony.", "effects": {"right":-1}},
    {"id": 59, "question": "I should be able to work unpaid extra time if I want to.", "effects": {"auth":-1}},
    {"id": 60, "question": "The government should be given a meritocratic wage system to ensure they don't fuck everything up.", "effects": {"auth":-1}},
    {"id": 61, "question": "Any \"democracy\" is a dictatorship if the government has no accountability for its actions.", "effects": {"auth":-1}},
    {"id": 62, "question": "Democracy is no more than a dictatorship of majority and should be removed, not reformed.", "effects": {"auth":1}},
    {"id": 63, "question": "Those who revised communism betrayed the revolution and should've been executed.", "effects": {"right":-1}},
    {"id": 64, "question": "Every company should make a different thing to ensure we have enough of everything. This should be enforced by the government.", "effects": {"right":-1}},
    {"id": 65, "question": "Unitary governments are a dictatorship of the elitist parliamentaries.", "effects": {"auth":-1}},
    {"id": 66, "question": "The state needs to permanently disappear.", "effects": {"auth":-1.5}},
    {"id": 67, "question": "Anarchism will eventually turn into a dictatorship through tribal-esque warfare.", "effects": {"auth":1}},
    {"id": 68, "question": "Genocide is based!!", "effects": {"auth":1}},
    {"id": 69, "question": "I don’t have anything against employers existing, but they must be elected by the workers within the workplace and they are subject to the state via a state-owned labor union.", "effects": {"right":-1, "auth":1}},
    {"id": 70, "question": "There should be one trade-union and it should be loyal to the state.", "effects": {"auth":1, "right":-1}},
    {"id": 71, "question": "I'm not pro-genocide but people should stay with their kind.", "effects": {"prog":-1}},
    {"id": 72, "question": "The monarchies in all countries should be absolute.", "effects": {"auth":1}},
    {"id": 73, "question": "Ayn Rand was the best philosopher in history.", "effects": {"auth":-1.75,"right":2.25}},
    {"id": 74, "question": "China's national trade union which allows for democratic elections of managers comes close to what I want.", "effects": {"auth":1,"right":-1}}
];
